[package]
name = "abc182"
version = "0.1.0"
authors = ["kgSuzuki1994 <takuti0511@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = "0.3.6"